// Cada proyecto lleva su propio color de marca (accent) para que su identidad
// resalte dentro del marco monocromo del portafolio. Orden = por impacto.
export const projects = [
  {
    slug: "licoreria",
    name: "Licorería Better Call Saul",
    sector: "E-commerce · Retail",
    year: "2026",
    role: "Diseño, front-end y backend",
    accent: "#e0b352",
    shot: "/shots/licoreria.png",
    tagline: "Tienda y panel de control con base de datos real.",
    blurb:
      "E-commerce con catálogo servido desde Supabase, carrito y pedidos que se guardan en base de datos real. Incluye un panel de administración con analítica, inventario y estados de pedido. El proyecto más completo: diseño, front-end y backend.",
    highlights: [
      "Supabase: Postgres, Auth y Storage con RLS",
      "Panel admin: inventario, pedidos y dashboard de ventas",
      "Checkout que arma el pedido y lo abre en WhatsApp",
      "RPC atómico que descuenta stock en una transacción",
    ],
    stack: ["React", "Supabase", "React Query", "Zustand", "Recharts"],
    status: "En línea",
    live: "https://licoreria-better-call-saul.vercel.app/",
    admin: "https://licoreria-better-call-saul.vercel.app/admin",
    repo: "https://github.com/gcondezoy/licoreria-better-call-saul",
  },
  {
    slug: "gadem",
    name: "Gadem Carrocerías",
    sector: "Industrial · B2B",
    year: "2026",
    role: "Diseño y front-end",
    accent: "#e01e1a",
    shot: "/shots/gadem.png",
    tagline: "Sitio industrial 'tactical telemetry' para un fabricante.",
    blurb:
      "Web multipágina B2B con estética industrial oscura: blueprints técnicos dibujados en SVG, configurador de cotización paso a paso y catálogo de carrocerías para vehículos pesados. Sin fotos de stock, todo ilustrado a medida.",
    highlights: [
      "Multipágina con React Router",
      "Ilustraciones técnicas blueprint en SVG (sin fotos stock)",
      "Cotizador interactivo que termina en WhatsApp",
      "Micro-interacciones, FAQ y tabla comparativa",
    ],
    stack: ["React", "Vite", "React Router", "Tailwind"],
    status: "En línea",
    live: "https://gadem-web-lohp.vercel.app/",
    repo: null,
  },
  {
    slug: "lucong",
    name: "Inversiones Lucong",
    sector: "Construcción · Obras civiles",
    year: "2026",
    role: "Front-end y SEO",
    accent: "#6d8aa8",
    shot: "/shots/lucong.png",
    tagline: "Sitio corporativo para una constructora en Lima.",
    blurb:
      "Web corporativa para una empresa de proyectos y ejecución de obras civiles. Presenta la empresa, su portafolio de obras y sus servicios, construida con Astro para máxima velocidad y con SEO cuidado en dominio propio.",
    highlights: [
      "Astro 6 con islas de React donde hacen falta",
      "Portafolio de obras y catálogo de servicios",
      "SEO con sitemap y buenas prácticas",
      "Desplegado en dominio propio (.com.pe)",
    ],
    stack: ["Astro", "React", "Tailwind"],
    status: "En línea",
    live: "https://www.inversioneslucong.com.pe/",
    repo: null,
  },
  {
    slug: "laindustrial",
    name: "La Industrial",
    sector: "Industrial · B2B",
    year: "2026",
    role: "Front-end, SEO y despliegue",
    accent: "#f5821f",
    shot: "/shots/laindustrial.png",
    tagline: "Web corporativa con SEO en producción.",
    blurb:
      "Sitio multipágina para Carrocerías La Industrial (Puente Piedra). Paquete SEO completo, formulario sin backend con Web3Forms y ficha de Google Business, ya con dominio propio y Search Console verificado.",
    highlights: [
      "React 19 y React Router 7 con SCSS por componente",
      "SEO: sitemap, JSON-LD LocalBusiness y canonical por página",
      "Formulario client-side con Web3Forms",
      "Dominio propio y Search Console verificado",
    ],
    stack: ["React 19", "Vite", "React Router", "SCSS"],
    status: "En línea",
    live: "https://www.carroceriaslaindustrial.com.pe",
    repo: "https://github.com/gcondezoy/la-industrial",
  },
  {
    slug: "mafille",
    name: "Mafille Belleza",
    sector: "Salón de belleza · Bienestar",
    year: "2026",
    role: "Diseño y front-end",
    accent: "#d17b8f",
    shot: "/shots/mafille.png",
    tagline: "Landing de alta gama para un salón holístico.",
    blurb:
      "Landing de una sola página para un salón de belleza y centro holístico en Los Olivos. Estética premium, animaciones cinemáticas y reserva directa por WhatsApp.",
    highlights: [
      "Dirección high-end: Cormorant Garamond + Plus Jakarta Sans",
      "SEO técnico: JSON-LD, Open Graph y mapa embebido",
      "WhatsApp flotante y marquee de servicios",
      "Desplegada en Vercel",
    ],
    stack: ["React", "Vite", "Tailwind v4"],
    status: "En línea",
    live: "https://mafille-belleza.vercel.app/",
    repo: "https://github.com/gcondezoy/mafille-belleza",
  },
  {
    slug: "florence",
    name: "La Florence",
    sector: "Florería boutique",
    year: "2026",
    role: "Diseño y front-end",
    accent: "#b9986a",
    shot: "/shots/florence.png",
    tagline: "Sitio editorial 'luxury' de estética francesa.",
    blurb:
      "Sitio multipágina estático con dirección editorial: serif Cormorant, grano de papel y movimiento cinemático. Catálogo filtrable y pedidos por WhatsApp, escrito a mano sin framework para que pese lo mínimo.",
    highlights: [
      "HTML, CSS y JavaScript a mano, sin build",
      "Catálogo con filtros por categoría",
      "Reveal por scroll y menú móvil con glass",
      "Sprite SVG con monograma y separadores botánicos",
    ],
    stack: ["HTML", "CSS", "JavaScript"],
    status: "En línea",
    live: "https://la-florence-floreria.vercel.app/",
    repo: null,
  },
]
